#!/usr/bin/env bash

function _is_running() {
	local IMAGE=$1
	local CONTAINER_NAME=$2
	local DOCKER_PS=$(docker ps --format "{{.Image}} {{.Names}}")
	if [ "$DOCKER_PS" != "${IMAGE} ${CONTAINER_NAME}" ]; then
	  echo "Container not found in:"
	  docker ps
	  return 1
	fi
}

function _hash() {
	local BINARY=$1

	if [ -z $BINARY ]; then
		echo "Cannot assert hash without an argument"
		return 1
	fi

	if ! hash $BINARY 2>/dev/null; then
		echo "${BINARY} not found"
		return 1
	fi
}

function _in_docker_group() {
	local USER=$(whoami)
	local GROUP_MEMBERS=$(cat /etc/group | awk -F':' '/docker/{print $4}')
	if ! grep -qw "${USER}" <<< $GROUP_MEMBERS; then
		echo "${USER} not found in:"
		echo "${GROUP_MEMBERS}"
		return 1
	fi
}

function assert() {
	local command=$1
	shift;
	echo "Asserting [ ${command} ] >>> ${@}"
	\_$command $@
	if [ $? = 0 ]; then
		echo "Success!"
	else
		echo "Failed."
		return 1
	fi
}

assert $@
