#!/usr/bin/env bash

BASE_COMMANDS="browse check clone create dc destroy install ip pull recreate restart upgrade usage workspace"
WORKSPACE_COMMANDS="init add rm ls use current upgrade"

tarantino() {
	tt $@
}

tt_complete() {
	local word=''
	local cmd=''
	local args=0
	while [[ $# -gt 1 ]]; do
		case "$1" in
		-w|--word)
			word=`echo $2 | tr -d "\""`
			shift ;;
		-c|--cmd)
			cmd=`echo $2 | tr -d "\""`
			shift ;;
		-a|--args)
			args=$2
			shift ;;
		esac
		shift
	done

	if [ $args -gt 3 ]; then
		#multi arg case
		case "$cmd" in
		create)
			completion_all_services $word ;;
		destroy|recreate)
			completion_running_services $word ;;
		pull|clone|check)
			completion_services $word ;;
		esac
	else
		#single arg case
		case "$cmd" in
		tt|"")
			completion_base $word ;;
		create|browse)
			completion_all_services $word ;;
		destroy|recreate|ip)
			completion_running_services $word ;;
		pull|clone|check)
			completion_services $word ;;
		workspace)
			completion_workspace $word ;;
		esac
	fi
}

completion_base() {
	echo "$BASE_COMMANDS"
}

completion_all_services() {
	tarantino get_all_services 2> /dev/null
}

completion_services() {
	tarantino get_services_with_source 2> /dev/null
}

completion_running_services() {
	local running_ids=$(docker ps -q)
	if [ ! -z "$running_ids" ]; then
		docker inspect --format \
			'{{index .Config.Labels "com.docker.compose.project"}} {{index .Config.Labels "com.docker.compose.service"}}' \
			$running_ids | sed -n "s/^$(tarantino get_workspace) //p"
	fi
}

completion_workspace() {
	echo "$WORKSPACE_COMMANDS"
}

tt_complete $@
