version: 2

aliases:

  - &remote_docker
    setup_remote_docker:
      version: 17.10.0-ce

  - &install_tt
    run:
      name: install tarantino
      command: |
        sudo -E make install

  - &create_test_workspace
    run:
      name: create "test" workspace
      command: |
        mkdir -p ~/projects
        mkdir -p ~/test_workspace
        pushd ~/test_workspace
        tt workspace init
        popd

  - &cleanup_containers
    run:
      name: clean up all containers
      command: "docker ps -qa | xargs -r docker rm -fv"
      when: always

  - &sync-submodules
    run:
      name: Sync up submodules
      command: |
        git submodule sync
        git submodule update --init


jobs:
  install:
    docker:
      - image: darrenmce/tt-test-install
    steps:
      - checkout
      - *sync-submodules
      - *install_tt
      - run:
          name: Validate Install
          command: test/valid_install.bats

  dockerTests:
    docker:
      - image: darrenmce/tt-test-base
    steps:
      - checkout
      - *sync-submodules
      - *remote_docker
      - *install_tt
      - *create_test_workspace
      - run:
          name: Basic Mongo Tests
          command: test/basic_mongo.bats
      - *cleanup_containers

  noDockerTests:
    docker:
      - image: darrenmce/tt-test-base
    steps:
      - checkout
      - *sync-submodules
      - *install_tt
      - run:
          name: Workspace tests
          command: test/workspace.bats

workflows:
  version: 2
  test:
    jobs:
      - install
      - dockerTests
      - noDockerTests