version: 2

aliases:

  - &remote_docker
    setup_remote_docker:
      version: 17.10.0-ce

  - &install_tt
    run:
      name: install tarantino
      command: |
        sudo -E make install

  - &create_test_workspace
    run:
      name: create "test" workspace
      command: |
        mkdir -p ~/projects
        mkdir -p ~/test_workspace
        pushd ~/test_workspace
        tt workspace init
        popd

  - &cleanup_containers
    run:
      name: clean up all containers
      command: "docker ps -qa | xargs -r docker rm -fv"

jobs:
  install:
    docker:
      - image: darrenmce/tt-test-install
    steps:
      - checkout
      - *install_tt
      - run:
          name: Validate Install
          command: test/valid_install.bats

  basic:
    docker:
      - image: darrenmce/tt-test-base
    steps:
      - checkout
      - *remote_docker
      - *install_tt
      - *create_test_workspace
      - run:
          name: Usage
          command: tt usage
      - run:
          name: Create Mongo
          command: tt create mongo
      - run:
          name: Assert Mongo is up
          command: test/assert is_running "mongo" "testworkspace_mongo_1"
      - run:
          name: Recreate Mongo
          command: tt recreate mongo
      - run:
          name: Assert Mongo is back up
          command: test/assert is_running "mongo" "testworkspace_mongo_1"
      - run:
          name: Destroy Mongo
          command: tt destroy mongo
      - run:
          name: Assert Mongo is destroyed
          command: test/assert container_destroyed "mongo" "testworkspace_mongo_1"
      - *cleanup_containers


workflows:
  version: 2
  test:
    jobs:
      - install
      - basic