version: 2

aliases:

  - &remote_docker
    setup_remote_docker:
      version: 17.10.0-ce

  - &install_tt
    run:
      name: install tarantino
      command: |
        sudo -E make install

  - &create_test_workspace
    run:
      name: create "test" workspace
      command: |
        mkdir -p ~/projects
        mkdir -p ~/test_workspace
        pushd ~/test_workspace
        tt workspace init
        popd

  - &cleanup_containers
    run:
      name: clean up all containers
      command: docker rm -fv $(docker ps -qa)
jobs:
  install:
    docker:
      - image: darrenmce/tt-test-install
    steps:
      - checkout
      - *install_tt

  basic:
    docker:
      - image: darrenmce/tt-test-base
    steps:
      - checkout
      - *remote_docker
      - *install_tt
      - *create_test_workspace
      - run:
          name: Usage
          command: tt usage
      - run:
          name: Create Mongo
          command: tt create mongo
      - run:
          name: Assert Mongo is up
          command: |
            DOCKER_PS=$(docker ps --format "{{.Image}} {{.Names}}")
            if [ "$DOCKER_PS" != "mongo testworkspace_mongo_1" ]; then
              exit 1
            fi
      - *cleanup_containers

workflows:
  version: 2
  test:
    jobs:
      - install
      - basic