#!/bin/bash

add_datasource() {
  until curl localhost:3000 &> /dev/null; do
    sleep 0.25
    echo Waiting for grafana to start...
  done

  echo Adding graphite data source.
  curl localhost:3000/api/datasources -d '{
    "name": "graphite",
    "type": "graphite",
    "url": "http://graphite",
    "isDefault": true,
    "access": "proxy",
    "basicAuth": false
  }' -H "content-type: application/json"
}

add_datasource &
exec /run.sh

