version: '2'
services:

  ####### infrastructure

  elasticsearch:
    image: elasticsearch

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_NAME: 'Main Org.'
      GF_AUTH_ANONYMOUS_ORG_ROLE: 'Admin'
      GF_DASHBOARDS_JSON_ENABLED: 'true'
      GF_DASHBOARDS_JSON_PATH: '/dashboards'
    volumes:
      - /etc/localtime:/etc/localtime:ro
#      - ${TT_PROJECTS}/grafana/grafana/app/dashboards:/dashboards:ro
    links:
      - graphite
      - elasticsearch

  graphite:
    image: hopsoft/graphite-statsd
    ports:
      - "80:80"
      - "2003:2003"
      - "8125:8125/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro

#  kibana:
#    build: ./kibana
#    environment:
#      KIBANA_SECURE: 'false'
#    links:
#      - elasticsearch:es

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  ####### services

  jackie:
    image: mhart/alpine-node
    command: node .
    environment:
      jackie_mongo__url: mongodb://mongo/jackie
      jackie_stats__host: graphite
    links:
      - elasticsearch
      - graphite
      - mongo
    volumes:
      - ${TT_PROJECTS}/jackie:/app:ro
    working_dir: /app

  jules:
    image: mhart/alpine-node
    command: node .
    environment:
      jules_jackie: http://jackie:8080
      jules_stats__host: graphite
    links:
      - elasticsearch
      - graphite
      - mongo
    volumes:
      - ${TT_PROJECTS}/jules:/app:ro
    working_dir: /app
