version: '2'
services:

  ####### infrastructure

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  ####### services

  jackie:
    image: mhart/alpine-node
    command: node .
    environment:
      jackie_mongo__url: mongodb://mongo/jackie
      jackie_stats__host: graphite
    links:
      - graphite
      - mongo
    volumes:
      - ${TT_PROJECTS}/jackie:/app:ro
    working_dir: /app

  jules:
    image: mhart/alpine-node
    command: node .
    environment:
      jules_jackie: http://jackie:8080
      jules_stats__host: graphite
    links:
      - graphite
      - mongo
    volumes:
      - ${TT_PROJECTS}/jules:/app:ro
    working_dir: /app
